Feature/weekly reset
Lambda-School-Labs/Labs26-StorySquad-BE-TeamB pull request #64
Opened 2020-12-17 17:28 UTC by ajg7

# Description

Fixes #

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2020-12-17 18:11 UTC, gregory-j-wilson requested changes
is all the stuff deleted ok to delete?

2020-12-17 18:27 UTC, ajg7 reviewed
Yep that stuff is ok to delete

2020-12-17 18:29 UTC, gregory-j-wilson commented
great.

2020-12-17 18:30 UTC, gregory-j-wilson submitted a review, later dismissed

2020-12-17 18:43 UTC, DeeDowns approved these changes, later dismissed

2020-12-17 18:43 UTC, DeeDowns commented on api/cronTasks/scheduler.js
>  const cron = require('node-cron');
So what this is doing on schedule determining who the winning team is and then assigning the points to the child? So the total points won in the matchup only go to a child of the winning team? Or the points go to the child who's submission was voted best?

2020-12-17 20:50 UTC, Nicci498 approved these changes, later dismissed

2020-12-18 04:28 UTC, gregory-j-wilson approved these changes
cool

2020-12-19 00:03 UTC, DeeDowns approved these changes

2020-12-19 00:04 UTC, merged